name: Build & Deploy Spring App

on:
  push:
    branches:
      - main  

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot for Beginners
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Setup JDK 17 for the project
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      # ✅ Run Unit Tests
      - name: Run Unit Tests
        run: mvn -B test --file pom.xml

      # ✅ Build the Application
      - name: Build the Application
        run: |  
          mvn clean
          mvn -B package --file pom.xml

      # ✅ Set the current date for Docker tagging
      - name: Set Date for Docker Tag
        id: date
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H-%M-%S')"

      # ✅ Build Docker Image without pushing it yet
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .   # Path to your Dockerfile (root of the repo)
          dockerfile: Dockerfile  # Name of the Dockerfile
          push: false  # Build but don't push yet
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:${{ steps.date.outputs.timestamp }}  # Tag with Docker Hub username and timestamp

      # ✅ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # ✅ Push the Docker Image to Docker Hub
      - name: Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .  # Path to your Dockerfile
          dockerfile: Dockerfile  # Dockerfile name
          push: true  # Push the image to the registry
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:${{ steps.date.outputs.timestamp }}  # Tagging with timestamp

